/* Regenerates cities.js — the offline place-name table used to label trips.
 *
 *   npm install all-the-cities
 *   node build-cities.js
 *
 * Source is GeoNames, via the all-the-cities package. Only settlements of 5,000
 * people or more are kept, which is the point where the file stops growing
 * faster than its usefulness.
 */

const fs = require('fs');
const cities = require('all-the-cities');

// GeoNames feature codes to discard:
//   PPLX  section of a populated place — i.e. a neighborhood. Without this,
//         central Barcelona resolves to "Eixample" and downtown San Francisco
//         to "Chinatown", because those entries sit closer than the city itself.
//   PPLQ  abandoned      PPLH  historical      PPLW  destroyed
const DROP = new Set(['PPLX', 'PPLQ', 'PPLH', 'PPLW']);
const MIN_POPULATION = 5000;

const rows = cities
  .filter(c => c.population >= MIN_POPULATION && !DROP.has(c.featureCode))
  .map(c => [
    +c.loc.coordinates[1].toFixed(3),   // latitude, ~110 m precision
    +c.loc.coordinates[0].toFixed(3),   // longitude
    String(c.name).replace(/[|\r\n]/g, ' ').trim()
  ])
  .filter(r => r[2] && Number.isFinite(r[0]) && Number.isFinite(r[1]))
  .sort((a, b) => a[0] - b[0]);         // sorted by latitude, matching the runtime index

const payload = rows.map(r => r.join('|')).join('\n');

const header = `/* Offline place-name table for Trip Map.
   Generated by build-cities.js — do not edit by hand.
   Source: GeoNames via the all-the-cities npm package, every settlement with a
   population of ${MIN_POPULATION.toLocaleString()} or more, excluding neighborhood-level entries.
   Coordinates rounded to three decimals (~110 m), far finer than the 30 km
   match radius needs.
   Format: one city per line, "latitude|longitude|name", sorted by latitude.
   Generated ${new Date().toISOString().slice(0, 10)} — ${rows.length.toLocaleString()} cities. */
`;

fs.writeFileSync('cities.js', header + 'window.CITY_DATA = ' + JSON.stringify(payload) + ';\n');

console.log(`cities.js written — ${rows.length.toLocaleString()} cities, ` +
            `${(fs.statSync('cities.js').size / 1048576).toFixed(2)} MB`);
